services:
  stereo_app:
    build: .
    ports:
      - "5000:5000"
    environment:
      CAMERA_SETTINGS_PATH: /app/config/cameras.json
    volumes:
      - "./camera-config:/app/config"
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
      - "/dev/video2:/dev/video2"
      - "/dev/video3:/dev/video3"